"""Common table for iterative searches

Revision ID: 0f78de238eef
Revises: e3c40c09577d
Create Date: 2018-08-17 14:45:12.540349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import sessionmaker, relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, ForeignKey, Table, Text, create_engine, Float, BLOB, DateTime, Boolean

# revision identifiers, used by Alembic.
revision = '0f78de238eef'
down_revision = 'e3c40c09577d'
branch_labels = None
depends_on = None



BaseTable = declarative_base()

class SearchBase(BaseTable):
    __tablename__ = 'SearchBase'
    idSearch = Column('idSearch', Integer, primary_key=True)
    searchType = Column(String(50))
    QValueBases = relationship('QValueBase', back_populates='searchbase', cascade='all,delete')
    SearchName = Column('SearchName', String, unique=True)

class QValueBase(BaseTable):
    __tablename__ = 'QValueBase'
    idQValue = Column('idQValue', Integer, primary_key=True)
    idSearchBase = Column(Integer, ForeignKey('SearchBase.idSearch'))
    searchbase = relationship('SearchBase', back_populates='QValueBases')

class FilteredSearchResult(BaseTable):
    __tablename__ = 'FilteredSearchResult'
    idFilteredSearchResult = Column('idFilteredSearchResult', Integer, primary_key=True)
    idQValueBase = Column(Integer, ForeignKey('QValueBase.idQValue'))
    QValue = relationship('QValueBase', back_populates='filteredSearchResults')



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IterativeSearchRun',
    sa.Column('idIterativeSearchRun', sa.Integer(), nullable=False),
    sa.Column('IterativeSearchRunName', sa.String(), nullable=True),
    sa.Column('searchType', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idIterativeSearchRun'),
    sa.UniqueConstraint('IterativeSearchRunName')
    )
    op.create_table('IterativeRunMGFAssociation',
    sa.Column('iterativerun_id', sa.Integer(), nullable=False),
    sa.Column('mgf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['iterativerun_id'], ['IterativeSearchRun.idIterativeSearchRun'], ),
    sa.ForeignKeyConstraint(['mgf_id'], ['MGFfile.idMGFfile'], ),
    sa.PrimaryKeyConstraint('iterativerun_id', 'mgf_id')
    )
    op.create_table('IterativeRunSearchAssociation',
    sa.Column('iterativerun_id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['iterativerun_id'], ['IterativeSearchRun.idIterativeSearchRun'], ),
    sa.ForeignKeyConstraint(['search_id'], ['SearchBase.idSearch'], ),
    sa.PrimaryKeyConstraint('iterativerun_id', 'search_id')
    )
    op.create_table('IterativeFilteredSearchAssociation',
    sa.Column('iterative_id', sa.Integer(), nullable=False),
    sa.Column('filteredsearch_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filteredsearch_id'], ['FilteredSearchResult.idFilteredSearchResult'], ),
    sa.ForeignKeyConstraint(['iterative_id'], ['IterativeSearchRun.idIterativeSearchRun'], ),
    sa.PrimaryKeyConstraint('iterative_id', 'filteredsearch_id')
    )
    bind = op.get_bind()
    Session = sessionmaker(bind=bind)
    session = Session()
    iterative_run_mgf_association_inserts = []
    iterative_run_search_association_inserts = []
    iterative_filtered_search_association_inserts = []
    iterative_search_run_inserts = []

    tide_iterative_run = sa.Table('TideIterativeRun', metadata, sa.Column('idTideIterativeRun', sa.Integer, primary_key=True), sa.Column('TideIterativeRunName', sa.String))
    msgf_iterative_run = sa.Table('MSGFPlusIterativeRun', metadata, sa.Column('idMSGFPlusIterativeRun', sa.Integer, primary_key=True), sa.Column('MSGFPlusIterativeRunName', sa.String))
    msgf_iterative_run_mgf_association = sa.Table('MSGFPlusIterativeRunMGFAssociation', metadata, sa.Column('msgfiterativerun_id', sa.Integer, sa.ForeignKey('MSGFPlusIterativeRun.idMSGFPlusIterativeRun'), primary_key=True), sa.Column('mgf_id', sa.Integer, sa.ForeignKey('MGFfile.idMGFfile', primary_key=True)))
    tide_iterative_run_mgf_association = sa.Table('TideIterativeRunMGFAssociation', metadata, sa.Column('tideiterativerun_id', sa.Integer, sa.ForeignKey('TideIterativeRun.idTideIterativeRun'), primary_key=True), sa.Column('mgf_id', sa.Integer, sa.ForeignKey('MGFfile.idMGFfile', primary_key=True)))
    msgf_iterative_run_filteredsearch_association = sa.Table('MSGFPlusIterativeFilteredSearchAssociation', metadata, sa.Column('msgfplusiterative_id', sa.Integer, sa.ForeignKey('MSGFPlusIterativeRun.idMSGFPlusIterativeRun'), primary_key=True), sa.Column('filteredsearch_id', sa.Integer, sa.ForeignKey('FilteredSearchResult.idFilteredSearchResult'), primary_key=True), sa.Column('step', sa.Integer))

    tide_iterative_filteredsearch_association = sa.Table('TideIterativeFilteredSearchAssociation', metadata, sa.Column('tideiterative_id', sa.Integer, sa.ForeignKey('TideIterativeRun.idTideIterativeRun'), primary_key=True), sa.Column('filteredsearch_id', sa.Integer, sa.ForeignKey('FilteredSearchResult.idFilteredSearchResult'), primary_key=True), sa.Column('step', sa.Integer))
    
    max_id = 0
    for row in connection.execute(sa.select([tide_iterative_run])):
        if row.idTideIterativeRun > max_id:
            max_id = row.idTideIterativeRun
            
    """
    Assign new IDs to the rows in MSGFPlusIterativeRun. Change the IDs in MSGFPlusIterativeRunMGFAssociation and MSGFPlusIterativeFilteredSearchAssociation
    """
    new_id = max_id + 1
    for row in connection.execute(sa.select([msgf_iterative_run])):
        old_id = row.idMSGFPlusIterativeRun
        op.execute(msgf_iterative_run.update().where(msgf_iterative_run.c.idMSGFPlusIterativeRun == old_id).values({'idMSGFPlusIterativeRun': new_id}))
        op.execute(msgf_iterative_run_mgf_association.update().where(msgf_iterative_run_mgf_association.c.msgfiterativerun_id == old_id).values({'msgfiterativerun_id': new_id}))
        op.execute(msgf_iterative_run_filteredsearch_association.update().where(msgf_iterative_run_filteredsearch_association.c.msgfiterative_id == old_id).values({'msgfiterative_id': new_id}))
        new_id += 1

    ids = []
    for row in connection.execute(sa.select([msgf_iterative_run])):
        ids.append(row.idMSGFPlusIterativeRun)
        new_row = {'iterativerun_id': row.idMSGFPlusIterativeRun, 'mgf_id': row.mgf_id}
        iterative_run_mgf_association_inserts.append(new_row)
    for row in connection.execute(sa.select([tide_iterative_run])):
        ids.append(row.idTideIterativeRun)
        new_row = {'iterativerun_id': row.idTideIterativeRun, 'mgf_id': row.mgf_id}
        iterative_run_mgf_association_inserts.append(new_row)
    #assert no repeats in ids between the two tables
    assert(len(ids) == len(set(ids)))
    """
    Merge MSGFPlusIterativeRunMGFAssociation and TideIterativeRunMGFAssociation into IterativeRunMGFAssociation
    """
    iterative_run_mgf_association = sa.Table('IterativeRunMGFAssociation', metadata, sa.Column('iterativerun_id', sa.Integer, sa.ForeignKey('IterativeSearchRun.idIterativeSearchRun'), primary_key=True), sa.Column('mgf_id', sa.Integer, sa.ForeignKey('MGFfile.idMGFfile'), primary_key=True))
    op.bulk_insert(iterative_run_mgf_association, iterative_run_mgf_association_inserts)

    
    iterative_filtered_search_association = sa.Table('IterativeFilteredSearchAssociation', metadata, sa.Column('iterative_id', sa.Integer, sa.ForeignKey('IterativeSearchRun.idIterativeSearchRun'), primary_key=True), sa.Column('filteredsearch_id', sa.Integer, sa.ForeignKey('FilteredSearchResult.idFilteredSearchResult'), primary_key=True), sa.Column('step', sa.Integer))
    
    ids = []
    for row in connection.execute(sa.select([msgf_iterative_run_filteredsearch_association])):
        ids.append(row.msgfplusiterative_id)
        new_row = {'iterative_id': row.msgfplusiterative_id, 'filteredsearch_id': row.filteredsearch_id}
        iterative_filtered_search_association_inserts.append(new_row)
    for row in connection.execute(sa.select([tide_iterative_filteredsearch_association])):
        ids.append(row.tideiterative_id)
        new_row = {'iterative_id': row.tideiterative_id, 'filteredsearch_id': row.filteredsearch_id}
        iterative_filtered_search_association_inserts.append(new_row)
    assert(len(ids) == len(set(ids)))
    op.bulk_insert(iterative_filtered_search_association, iterative_filtered_search_association_inserts)
    
    
    """
    Create IterativeRunSearchAssociation. This links IterativeSearchRun with the searches in it.
    """
    iterative_run_search_association = sa.Table('IterativeRunSearchAssociation', metadata, sa.Column('iterativerun_id', sa.Integer, sa.ForeignKey('IterativeSearchRun.idIterativeSearchRun'), primary_key=True), sa.Column('search_id', sa.Integer, sa.ForeignKey('SearchBase.idSearch'), primary_key=True))

    
    for row in connection.execute(sa.select([msgf_iterative_run_filteredsearch_association])):
        iterative_id = row.msgfplusiterative_id
        filtered_id = row.filteredsearch_id
        filtered_row = session.query(FilteredSearchResult).filter_by(idFilteredSearchResult = filtered_id).first()
        assert(filtered_row)
        qvalue_row = filtered_row.QValue
        search_row = qvalue_row.searchbase
        iterative_search_run_inserts.append({'iterativerun_id': iterative_id, 'search_id': search_row.idSearchBase})
    for row in connection.execute(sa.select([tide_iterative_filteredsearch_association])):
        iterative_id = row.tideiterative_id
        filtered_id = row.filteredsearch_id
        filtered_row = session.query(FilteredSearchResult).filter_by(idFilteredSearchResult = filtered_id).first()
        assert(filtered_row)
        qvalue_row = filtered_row.QValue
        search_row = qvalue_row.searchbase
        iterative_search_run_inserts.append({'iterativerun_id': iterative_id, 'search_id': search_row.idSearchBase})
    
    op.bulk_insert(iterative_run_search_association, iterative_search_run_inserts)
    
    op.drop_table('MSGFPlusIterativeRunMGFAssociation')
    op.drop_table('TideIterativeRunMGFAssociation')
    op.drop_table('TideIterativeFilteredSearchAssociation')
    op.drop_table('MSGFPlusIterativeFilteredSearchAssociation')
    with op.batch_alter_table('AssignConfidence', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_assignconfidence', 'AssignConfidenceParameterFile', ['idParameterFile'], ['idAssignConfidenceParameterFile'])

    with op.batch_alter_table('MSGFPlusIterativeRun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idIterativeSearchRun', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.create_foreign_key('fk_iterativerunmsgf', 'IterativeSearchRun', ['idIterativeSearchRun'], ['idIterativeSearchRun'])
        batch_op.drop_column('idMSGFPlusIterativeRun')
        batch_op.drop_column('MSGFPlusIterativeRunName')

    with op.batch_alter_table('TideIterativeRun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idIterativeSearchRun', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.create_foreign_key('fk_iterativeruntide', 'IterativeSearchRun', ['idIterativeSearchRun'], ['idIterativeSearchRun'])
        batch_op.drop_column('idTideIterativeRun')
        batch_op.drop_column('TideRunName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TideIterativeRun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TideRunName', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('idTideIterativeRun', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idIterativeSearchRun')

    with op.batch_alter_table('MSGFPlusIterativeRun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MSGFPlusIterativeRunName', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('idMSGFPlusIterativeRun', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idIterativeSearchRun')

    with op.batch_alter_table('AssignConfidence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('MSGFPlusIterativeFilteredSearchAssociation',
    sa.Column('msgfplusiterative_id', sa.INTEGER(), nullable=False),
    sa.Column('filteredsearch_id', sa.INTEGER(), nullable=False),
    sa.Column('step', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['filteredsearch_id'], ['FilteredSearchResult.idFilteredSearchResult'], ),
    sa.ForeignKeyConstraint(['msgfplusiterative_id'], ['MSGFPlusIterativeRun.idMSGFPlusIterativeRun'], ),
    sa.PrimaryKeyConstraint('msgfplusiterative_id', 'filteredsearch_id')
    )
    op.create_table('TideIterativeFilteredSearchAssociation',
    sa.Column('tideiterative_id', sa.INTEGER(), nullable=False),
    sa.Column('filteredsearch_id', sa.INTEGER(), nullable=False),
    sa.Column('step', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['filteredsearch_id'], ['FilteredSearchResult.idFilteredSearchResult'], ),
    sa.ForeignKeyConstraint(['tideiterative_id'], ['TideIterativeRun.idTideIterativeRun'], ),
    sa.PrimaryKeyConstraint('tideiterative_id', 'filteredsearch_id')
    )
    op.create_table('TideIterativeRunMGFAssociation',
    sa.Column('tideiterativerun_id', sa.INTEGER(), nullable=False),
    sa.Column('mgf_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mgf_id'], ['MGFfile.idMGFfile'], ),
    sa.ForeignKeyConstraint(['tideiterativerun_id'], ['TideIterativeRun.idTideIterativeRun'], ),
    sa.PrimaryKeyConstraint('tideiterativerun_id', 'mgf_id')
    )
    op.create_table('MSGFPlusIterativeRunMGFAssociation',
    sa.Column('msgfiterativerun_id', sa.INTEGER(), nullable=False),
    sa.Column('mgf_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mgf_id'], ['MGFfile.idMGFfile'], ),
    sa.ForeignKeyConstraint(['msgfiterativerun_id'], ['MSGFPlusIterativeRun.idMSGFPlusIterativeRun'], ),
    sa.PrimaryKeyConstraint('msgfiterativerun_id', 'mgf_id')
    )
    op.drop_table('IterativeFilteredSearchAssociation')
    op.drop_table('IterativeRunSearchAssociation')
    op.drop_table('IterativeRunMGFAssociation')
    op.drop_table('IterativeSearchRun')
    # ### end Alembic commands ###
