"""MSGF+ Training

Revision ID: 98735d71cdbe
Revises: ba84174a3f83
Create Date: 2019-01-23 09:18:16.933486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98735d71cdbe'
down_revision = 'ba84174a3f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MSGFPlusTrainingParams',
    sa.Column('idMSGFPlusTrainingParams', sa.Integer(), nullable=False),
    sa.Column('trainingName', sa.String(), nullable=False),
    sa.Column('paramFileLocation', sa.String(), nullable=False),
    sa.Column('idMSGFPlusSearch', sa.Integer(), nullable=True),
    sa.Column('idMGF', sa.Integer(), nullable=True),
    sa.Column('fragmentationMethod', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Integer(), nullable=False),
    sa.Column('enzyme', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idMGF'], ['MGFfile.idMGFfile'], ),
    sa.ForeignKeyConstraint(['idMSGFPlusSearch'], ['MSGFPlusSearch.idSearch'], ),
    sa.PrimaryKeyConstraint('idMSGFPlusTrainingParams'),
    sa.UniqueConstraint('paramFileLocation'),
    sa.UniqueConstraint('trainingName')
    )
    with op.batch_alter_table('MGFfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enzyme', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fragmentationMethod', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instrument', sa.Integer(), nullable=True))

    with op.batch_alter_table('MSGFPlusSearch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idMSGFPlusSearch', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'MSGFPlusSearch', ['idMSGFPlusSearch'], ['idSearch'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('MSGFPlusSearch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('idMSGFPlusSearch')

    with op.batch_alter_table('MGFfile', schema=None) as batch_op:
        batch_op.drop_column('instrument')
        batch_op.drop_column('fragmentationMethod')
        batch_op.drop_column('enzyme')

    op.drop_table('MSGFPlusTrainingParams')
    # ### end Alembic commands ###
