"""Upgrading parameter file

Revision ID: 98a6ad0ea1f1
Revises: dfa8cf18fe61
Create Date: 2018-08-07 09:56:14.101639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a6ad0ea1f1'
down_revision = 'dfa8cf18fe61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AssignConfidence', sa.Column('idParemeterFile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'AssignConfidence', 'AssignConfidenceParameterFile', ['idParemeterFile'], ['idAssignConfidenceParameterFile'])
    op.alter_column('MSGFPlusSearch', 'addFeatures',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.add_column('MaxQuantSearch', sa.Column('idParameterFile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'MaxQuantSearch', 'MaxQuantParameterFile', ['idParameterFile'], ['idMaxQuantParameterFile'])
    op.add_column('Percolator', sa.Column('idParameterFile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Percolator', 'PercolatorParameterFile', ['idParameterFile'], ['idPercolatorParameterFile'])
    op.add_column('TideIndex', sa.Column('idParameterFile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'TideIndex', 'TideIndexParameterFile', ['idParameterFile'], ['idTideIndexParameterFile'])
    op.add_column('TideSearch', sa.Column('idParameterFile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'TideSearch', 'TideSearchParameterFile', ['idParameterFile'], ['idTideSearchParameterFile'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TideSearch', type_='foreignkey')
    op.drop_column('TideSearch', 'idParameterFile')
    op.drop_constraint(None, 'TideIndex', type_='foreignkey')
    op.drop_column('TideIndex', 'idParameterFile')
    op.drop_constraint(None, 'Percolator', type_='foreignkey')
    op.drop_column('Percolator', 'idParameterFile')
    op.drop_constraint(None, 'MaxQuantSearch', type_='foreignkey')
    op.drop_column('MaxQuantSearch', 'idParameterFile')
    op.alter_column('MSGFPlusSearch', 'addFeatures',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint(None, 'AssignConfidence', type_='foreignkey')
    op.drop_column('AssignConfidence', 'idParemeterFile')
    # ### end Alembic commands ###
