"""Use FASTA file for MSGF+ index

Revision ID: ba84174a3f83
Revises: 0f78de238eef
Create Date: 2019-01-11 11:47:38.834041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba84174a3f83'
down_revision = '0f78de238eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msgfplus_index_fasta',
    sa.Column('msgfplus_index_id', sa.Integer(), nullable=False),
    sa.Column('fasta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fasta_id'], ['FASTA.idFASTA'], ),
    sa.ForeignKeyConstraint(['msgfplus_index_id'], ['MSGFPlusIndex.idIndex'], ),
    sa.PrimaryKeyConstraint('msgfplus_index_id', 'fasta_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msgfplus_index_fasta')
    # ### end Alembic commands ###
