"""Multiple NetMHC runs for FilterNetMHC.py

Revision ID: e9772fac9738
Revises: 0f78de238eef
Create Date: 2020-01-29 16:16:38.839679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9772fac9738'
down_revision = '0f78de238eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filteredNetMHC_netMHC',
    sa.Column('filteredNetMHC_id', sa.Integer(), nullable=False),
    sa.Column('netMHC_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filteredNetMHC_id'], ['FilteredNetMHC.idFilteredNetMHC'], ),
    sa.ForeignKeyConstraint(['netMHC_id'], ['NetMHC.idNetMHC'], ),
    sa.PrimaryKeyConstraint('filteredNetMHC_id', 'netMHC_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filteredNetMHC_netMHC')
    # ### end Alembic commands ###
