#!/bin/bash
cd ..
python3 RunIterativeTideSearch.py MurphyReplication Y3MGF 0.01 percolator Y3IterTideLargeToSmallPercolator CombinedUnfilteredIndex CombinedTwoPercentTideIndex CombinedOnePercentTideIndex --peptide_identifier_param_file murphy_replication/percolator.params --tidesearch_param_file murphy_replication/tide_search.params
python3 ExportPeptides MurphyReplication TideIterativeSearch Y3IterTideLargeToSmallPercolator murphy_replication/y3_iter_tide_large_to_small_percolator.txt
#python3 RunIterativeTideSearch.py MurphyReplication B22MGF 0.01 percolator B22IterTideLargeToSmallPercolator CombinedUnfilteredIndex CombinedTwoPercentTideIndex CombinedOnePercentTideIndex --peptide_identifier_param_file murphy_replication/percolator.params --tidesearch_param_file murphy_replication/tide_search.params 
#python3 ExportPeptides MurphyReplication TideIterativeSearch B22IterTideLargeToSmallPercolator murphy_replication/b22_iter_tide_large_to_small_percolator.txt
#python3 RunIterativeTideSearch.py MurphyReplication Y3MGF 0.01 assign-confidence Y3IterTideLargeToSmallAssignConfidence CombinedUnfilteredIndex CombinedTwoPercentTideIndex CombinedOnePercentTideIndex --tidesearch_param_file murphy_replication/tide_search.params
#python3 ExportPeptides MurphyReplication TideIterativeSearch Y3IterTideLargeToSmallAssignConfidence murphy_replication/y3_iter_tide_large_to_small_assign_confidence.txt
#python3 RunIterativeTideSearch.py MurphyReplication B22MGF 0.01 assign-confidence B22IterTideLargeToSmallAssignConfidence CombinedUnfilteredIndex CombinedTwoPercentTideIndex CombinedOnePercentTideIndex   --tidesearch_param_file murphy_replication/tide_search.params
#python3 ExportPeptides MurphyReplication TideIterativeSearch B22IterTideLargeToSmallAssignConfidence murphy_replication/b22_iter_tide_large_to_small_assign_confidence.txt

