#!/bin/bash
cd ..





python3 RunMSGFPlusSearch.py MurphyReplication Y3MGF CombinedOnePercentIndex Y3CombinedOnePercentMSGFSearch_features --thread 5 --memory 30000
python3 RunPercolator.py MurphyReplication Y3CombinedOnePercentMSGFSearch_features Y3CombinedOnePercentMSGFSearch_features_percolator --param_file murphy_replication/percolator.params
python3 FilterQValue.py MurphyReplication percolator Y3CombinedOnePercentMSGFSearchFilter_features_percolator 0.01 Y3CombinedOnePercentMSGFSearch_features_percolator_filtered 
python3 ExportPeptides.py MurphyReplication FilteredSearchResult Y3CombinedOnePercentMSGFSearch_features_percolator_filtered  murphy_replication/msgf_percolator_y3_onepercent.txt


python3 RunMSGFPlusSearch.py MurphyReplication B22MGF CombinedOnePercentIndex B22CombinedOnePercentMSGFSearch_features --thread 5 --memory 30000
python3 RunPercolator.py MurphyReplication B22CombinedOnePercentMSGFSearch_features B22CombinedOnePercentMSGFSearch_features_percolator --param_file murphy_replication/percolator.params
python3 FilterQValue.py MurphyReplication percolator B22CombinedOnePercentMSGFSearch_features_percolator 0.01 B22CombinedOnePercentMSGFSearchFilter_features_percolator_filtered
python3 ExportPeptides.py MurphyReplication FilteredSearchResult B22CombinedOnePercentMSGFSearchFilter_features_percolator_filtered murphy_replication/msgf_percolator_b22_onepercent.txt


python3 RunMSGFPlusSearch.py MurphyReplication Y3MGF CombinedTwoPercentIndex Y3CombinedTwoPercentMSGFSearch_features --thread 5 --memory 30000
python3 RunPercolator.py MurphyReplication Y3CombinedTwoPercentMSGFSearch_features Y3CombinedTwoPercentMSGFSearch_features_percolator --param_file murphy_replication/percolator.params
python3 FilterQValue.py MurphyReplication percolator Y3CombinedTwoPercentMSGFSearchFilter_features_percolator 0.01 Y3CombinedTwoPercentMSGFSearch_features_percolator_filtered 
python3 ExportPeptides.py MurphyReplication FilteredSearchResult Y3CombinedTwoPercentMSGFSearch_features_percolator_filtered  murphy_replication/msgf_percolator_y3_twopercent.txt


python3 RunMSGFPlusSearch.py MurphyReplication B22MGF CombinedTwoPercentIndex B22CombinedOnePercentMSGFSearch_features --thread 5 --memory 30000
python3 RunPercolator.py MurphyReplication B22CombinedTwoPercentMSGFSearch_features B22CombinedTwoPercentMSGFSearch_features_percolator --param_file murphy_replication/percolator.params
python3 FilterQValue.py MurphyReplication percolator B22CombinedTwoPercentMSGFSearch_features_percolator 0.01 B22CombinedTwoPercentMSGFSearchFilter_features_percolator_filtered
python3 ExportPeptides.py MurphyReplication FilteredSearchResult B22CombinedTwoPercentMSGFSearchFilter_features_percolator_filtered murphy_replication/msgf_percolator_b22_twopercent.txt

