#!/bin/bash
cd ..




#python3 AddParamFile.py MurphyReplication Percolator Main murphy_replication/percolator.params --comment "Nothing special"
#python3 RunMSGFPlusSearch.py MurphyReplication Y3MGF CombinedOnePercentIndex Y3CombinedOnePercentMSGFSearch_features --thread 5 --memory 30000
#python3 RunPercolator.py MurphyReplication msgfplus Y3CombinedOnePercentMSGFSearch_features Y3CombinedOnePercentMSGFSearch_features_percolator_final_two --param_file Main
#python3 FilterQValue.py MurphyReplication percolator Y3CombinedOnePercentMSGFSearch_features_percolator_final_two 0.01 Y3CombinedOnePercentMSGFSearch_features_percolator_filtered_two
python3 ExportPeptides.py MurphyReplication FilteredSearchResult Y3CombinedOnePercentMSGFSearch_features_percolator_filtered_two  murphy_replication/msgf_percolator_y3_onepercent.txt --overwrite True


#echo "Done with first part"

#python3 RunMSGFPlusSearch.py MurphyReplication B22MGF CombinedOnePercentIndex B22CombinedOnePercentMSGFSearch_features --thread 5 --memory 30000
#python3 RunPercolator.py MurphyReplication msgfplus B22CombinedOnePercentMSGFSearch_features B22CombinedOnePercentMSGFSearch_features_percolator_final_two --param_file Main
#python3 FilterQValue.py MurphyReplication percolator B22CombinedOnePercentMSGFSearch_features_percolator_final_two 0.01 B22CombinedOnePercentMSGFSearchFilter_features_percolator_filtered_two
#python3 ExportPeptides.py MurphyReplication FilteredSearchResult B22CombinedOnePercentMSGFSearchFilter_features_percolator_filtered_two murphy_replication/msgf_percolator_b22_onepercent.txt --overwrite True

#echo "done with second part"

#python3 RunMSGFPlusSearch.py MurphyReplication Y3MGF CombinedTwoPercentIndex Y3CombinedTwoPercentMSGFSearch_features --thread 5 --memory 30000
#python3 RunPercolator.py MurphyReplication msgfplus Y3CombinedTwoPercentMSGFSearch_features Y3CombinedTwoPercentMSGFSearch_features_percolator_final_two --param_file Main
#python3 FilterQValue.py MurphyReplication percolator Y3CombinedTwoPercentMSGFSearch_features_percolator_final_two 0.01 Y3CombinedTwoPercentMSGFSearch_features_percolator_filtered_two
#python3 ExportPeptides.py MurphyReplication FilteredSearchResult Y3CombinedTwoPercentMSGFSearch_features_percolator_filtered_two  murphy_replication/msgf_percolator_y3_twopercent.txt --overwrite True

#echo "done with third part"

#python3 RunMSGFPlusSearch.py MurphyReplication B22MGF CombinedTwoPercentIndex B22CombinedTwoPercentMSGFSearch_features --thread 5 --memory 30000
#python3 RunPercolator.py MurphyReplication msgfplus B22CombinedTwoPercentMSGFSearch_features B22CombinedTwoPercentMSGFSearch_features_percolator_final_two --param_file Main
#python3 FilterQValue.py MurphyReplication percolator B22CombinedTwoPercentMSGFSearch_features_percolator_final_two 0.01 B22CombinedTwoPercentMSGFSearchFilter_features_percolator_filtered_two
#python3 ExportPeptides.py MurphyReplication FilteredSearchResult B22CombinedTwoPercentMSGFSearchFilter_features_percolator_filtered_two murphy_replication/msgf_percolator_b22_twopercent.txt --overwrite True

echo "done with fourth part"
