#!/bin/bash
cd ..
python3 RunNetMHC.py MurphyReplication MouseProteinEightMers H-2-Kb 1 MouseProteinEightMersKbOnePercent
python3 RunNetMHC.py MurphyReplication MouseProteinNineMers H-2-Kb 1 MouseProteinNineMersKbOnePercent
python3 RunNetMHC.py MurphyReplication MouseProteinTenMers H-2-Kb 1 MouseProteinTenMersKbOnePercent
python3 RunNetMHC.py MurphyReplication MouseProteinElevenMers H-2-Kb 1 MouseProteinElevenMersKbOnePercent
python3 RunNetMHC.py MurphyReplication MouseProteinEightMers H-2-Db 1 MouseProteinEightMersDbOnePercent
python3 RunNetMHC.py MurphyReplication MouseProteinNineMers H-2-Db 1 MouseProteinNineMersDbOnePercent
python3 RunNetMHC.py MurphyReplication MouseProteinTenMers H-2-Db 1 MouseProteinTenMersDbOnePercent
python3 RunNetMHC.py MurphyReplication MouseProteinElevenMers H-2-Db 1 MouseProteinElevenMersDbOnePercent

python3 CreateTargetSet.py MurphyReplication --FilteredNetMHC MouseProteinEightMersKbOnePercent --FilteredNetMHC MouseProteinNineMersKbOnePercent --FilteredNetMHC MouseProteinTenMersKbOnePercent --FilteredNetMHC MouseProteinElevenMersKbOnePercent --FilteredNetMHC MouseProteinEightMersDbOnePercent --FilteredNetMHC MouseProteinNineMersDbOnePercent --FilteredNetMHC MouseProteinTenMersDbOnePercent --FilteredNetMHC MouseProteinElevenMersDbOnePercent  CombinedOnePercent



python3 RunMaxQuantSearch.py MurphyReplication Y3RAW MaxQuantConfig 0.01 TargetSet CombinedOnePercent OnePercentMaxQuantY3
python3 ExportPeptides.py MurphyReplication MaxQuantSearch OnePercentMaxQuantY3 murphy_replication/maxquant_y3_onepercent.txt
python3 CreateMSGFPlusIndex.py MurphyReplication TargetSet CombinedOnePercent CombinedOnePercentIndex --memory 30000
python3 RunMSGFPlusSearch.py MurphyReplication Y3MGF CombinedOnePercentIndex Y3CombinedOnePercentMSGFSearch --thread 5 --memory 30000
python3 FilterQValue.py MurphyReplication MSGF Y3CombinedOnePercentMSGFSearch 0.01 Y3CombinedOnePercentMSGFSearchFilter
python3 ExportPeptides.py MurphyReplication FilteredSearchResult Y3CombinedOnePercentMSGFSearchFilter murphy_replication/msgf_y3_onepercent.txt
python3 CreateTideIndex.py MurphyReplication TargetSet CombinedOnePercent CombinedOnePercentTideIndex --custom-enzyme '[Z]|[Z]' --enzyme custom-enzyme
python3 RunTideSearch.py MurphyReplication Y3MGF CombinedOnePercentTideIndex CombinedOnePercentY3TideSearch --num-threads 1 --top-match 1
python3 RunPercolator.py MurphyReplication CombinedOnePercentY3TideSearch CombinedOnePercentY3Percolator --param_file murphy_replication/percolator.params
python3 FilterQValue.py MurphyReplication percolator CombinedOnePercentY3Percolator 0.01 CombinedOnePercentY3PercolatorFiltered
python3 ExportPeptides.py MurphyReplication FilteredSearchResult CombinedOnePercentY3PercolatorFiltered murphy_replication/percolator_y3_onepercent.txt
python3 RunAssignConfidence.py MurphyReplication CombinedOnePercentY3TideSearch CombinedOnePercentY3TideSearchConfidence
python3 FilterQValue.py MurphyReplication assign_confidence CombinedOnePercentY3TideSearchConfidence 0.01 CombinedOnePercentY3TideSearchConfidenceFiltered
python3 ExportPeptides.py MurphyReplication FilteredSearchResult CombinedOnePercentY3TideSearchConfidenceFiltered murphy_replication/assign_confidence_y3_onepercent.txt

python3 RunMaxQuantSearch.py MurphyReplication B22RAW MaxQuantConfig 0.01 TargetSet CombinedOnePercent OnePercentMaxQuantB22
python3 ExportPeptides.py MurphyReplication MaxQuantSearch OnePercentMaxQuantB22 murphy_replication/maxquant_b22_onepercent.txt
python3 RunMSGFPlusSearch.py MurphyReplication B22MGF CombinedOnePercentIndex B22CombinedOnePercentMSGFSearch --thread 5 --memory 30000
python3 FilterQValue.py MurphyReplication MSGF B22CombinedOnePercentMSGFSearch 0.01 B22CombinedOnePercentMSGFSearchFilter
python3 ExportPeptides.py MurphyReplication FilteredSearchResult B22CombinedOnePercentMSGFSearchFilter murphy_replication/msgf_b22_onepercent.txt
python3 RunTideSearch.py MurphyReplication B22MGF CombinedOnePercentTideIndex CombinedOnePercentB22TideSearch --num-threads 1 --top-match 1
python3 RunPercolator.py MurphyReplication CombinedOnePercentB22TideSearch CombinedOnePercentB22Percolator --param_file murphy_replication/percolator.params
python3 FilterQValue.py MurphyReplication percolator CombinedOnePercentB22Percolator 0.01 CombinedOnePercentB22PercolatorFiltered
python3 ExportPeptides.py MurphyReplication FilteredSearchResult CombinedOnePercentB22PercolatorFiltered murphy_replication/percolator_b22_onepercent.txt
python3 RunAssignConfidence.py MurphyReplication CombinedOnePercentB22TideSearch CombinedOnePercentB22TideSearchConfidence
python3 FilterQValue.py MurphyReplication assign_confidence CombinedOnePercentB22TideSearchConfidence 0.01 CombinedOnePercentB22TideSearchConfidenceFiltered
python3 ExportPeptides.py MurphyReplication FilteredSearchResult CombinedOnePercentB22TideSearchConfidenceFiltered murphy_replication/assign_confidence_b22_onepercent.txt
