#!/bin/bash
cd ..
#python3 RunIterativeTideSearch.py MurphyReplication Y3MGF 0.01 percolator Y3IterTideSmallToLargePercolator CombinedOnePercentTideIndex  CombinedTwoPercentTideIndex CombinedUnfilteredIndex --peptide_identifier_param_file murphy_replication/percolator.params --tidesearch_param_file murphy_replication/tide_search.params > y3_iter_tide_small_to_large_percolator_output.txt &

#python3 RunIterativeTideSearch.py MurphyReplication B22MGF 0.01 percolator B22IterTideSmallToLargePercolator CombinedOnePercentTideIndex CombinedTwoPercentTideIndex  CombinedUnfilteredIndex --peptide_identifier_param_file murphy_replication/percolator.params --tidesearch_param_file murphy_replication/tide_search.params > b22_iter_tide_small_to_large_percolator_output.txt & 

#python3 RunIterativeTideSearch.py MurphyReplication Y3MGF 0.01 assign-confidence Y3IterTideSmallToLargeAssignConfidence CombinedOnePercentTideIndex  CombinedTwoPercentTideIndex CombinedUnfilteredIndex  --tidesearch_param_file murphy_replication/tide_search.params > y3_iter_tide_small_to_large_assign_confidence_output.txt &

#python3 RunIterativeTideSearch.py MurphyReplication B22MGF 0.01 assign-confidence B22IterTideSmallToLargeAssignConfidence CombinedOnePercentTideIndex CombinedTwoPercentTideIndex CombinedUnfilteredIndex   --tidesearch_param_file murphy_replication/tide_search.params > b22_iter_tide_small_to_large_assign_confidence_output.txt &


python3 ExportPeptides.py MurphyReplication TideIterativeSearch B22IterTideSmallToLargeAssignConfidence murphy_replication/b22_iter_tide_small_to_large_assign_confidence.txt
python3 ExportPeptides.py MurphyReplication TideIterativeSearch Y3IterTideSmallToLargePercolator murphy_replication/y3_iter_tide_small_to_large_percolator.txt
python3 ExportPeptides.py MurphyReplication TideIterativeSearch B22IterTideSmallToLargePercolator murphy_replication/b22_iter_tide_small_to_large_percolator.txt
python3 ExportPeptides.py MurphyReplication TideIterativeSearch Y3IterTideSmallToLargeAssignConfidence murphy_replication/y3_iter_tide_small_to_large_assign_confidence.txt
