cd ..

python3 RunPercolator.py HealthCenter tide CombinedTwoPercentTide_Prep CombinedTwoPercentTide_Prep_percolator
python3 RunPercolator.py HealthCenter tide CombinedOnePercentTide_Prep CombinedOnePercentTide_Prep_percolator
python3 RunPercolator.py HealthCenter tide CombinedTide_Prep CombinedTide_Prep_percolator


python3 RunPercolator.py HealthCenter tide CombinedTwoPercentTide_Run2 CombinedTwoPercentTide_Run2_percolator
python3 RunPercolator.py HealthCenter tide CombinedOnePercentTide_Run2 CombinedOnePercentTide_Run2_percolator
python3 RunPercolator.py HealthCenter tide CombinedTide_Run2 CombinedTide_Run2_percolator



python3 RunPercolator.py HealthCenter msgfplus CombinedTwoPercentMSGF_Prep CombinedTwoPercentMSGF_Prep_percolator
python3 RunPercolator.py HealthCenter msgfplus CombinedOnePercentMSGF_Prep CombinedOnePercentMSGF_Prep_percolator
python3 RunPercolator.py HealthCenter msgfplus CombinedMSGF_Prep CombinedMSGF_Prep_percolator


python3 RunPercolator.py HealthCenter msgfplus CombinedTwoPercentMSGF_Run2 CombinedTwoPercentMSGF_Run2_percolator
python3 RunPercolator.py HealthCenter msgfplus CombinedOnePercentMSGF_Run2 CombinedOnePercentMSGF_Run2_percolator
python3 RunPercolator.py HealthCenter msgfplus CombinedMSGF_Run2 CombinedMSGF_Run2_percolator

